name: linux-build

on: [push]

jobs:
  linux:
    strategy:
      matrix:
        compiler:
          - clang-8
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: tvm
        run: |
          cd ${{github.workspace}}/tvm
          git fetch --unshallow --tags --prune --force
      - name: build
        run: |
          cd ${{github.workspace}}/tvm
          cmake -B ${{github.workspace}}/tvm/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/tvm/build --config ${{env.BUILD_TYPE}}
          npm install
          npm run test
